# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Boaz Owitti
description: "I'm a data scientist providing cross industry solutions to client-centric business challenges, leveraging data to drive powerful insights that add value to the business. Proficient in translating complex business problems into actionable solutions, and employing data science expertise and creative problem-solving skills to real-world problems. Please visit my LinkedIn page and/or download my Resume by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New Jersey, U.S.A."
resume_url: /docs/resume.docx
avatar_image: /img/portfolio.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/boazowitti" # Add your linkedln handle
github: "https://boazowitti.github.io/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

